### ISSUE TITLE
Explain typedef in tutorial

### ISSUE THREAD

**Issue by oxygene** [zajo/boost-synapse#1]
I've started reading the turorial and immediately got stuck in the very first line. You tell the reader that defining signals is really easy, providing a typedef example.
However, the C++ syntax for function pointers is not very intuitive and not all casual C++ programmers immediately recognize them. It adds to the confusion that a forward declaration of a struct is also included in the typedef.

So maybe you should explain first that a signal in synapse is basically a typedef to a function pointer. And that we actually don't need a return type but we still want to use one just to make the typedef'ed types different for the compiler so that they cannot be mixed up by accident, resulting in a compilation error. As we are not going to use the return type, we can just create "throw-away" types by inline forward declaring a struct with deliberately chosen, but unique, name.

**Comment by zajo** [comment]
Late reply, but it's done now.
